// const MAIN_ROUTES = {
//     O2: [
//         {
//             streetName: "Trần Cao Vân (209-337)",
//             type: true,
//             isBoth: false,
//             firstNumber: 209,
//             lastNumber: 337,
//             route: "O2",
//         },
//         {
//             streetName: "Trần Cao Vân (342-624)",
//             type: true,
//             isBoth: false,
//             firstNumber: 342,
//             lastNumber: 426,
//             route: "O2",
//         },
//         {
//             streetName: "Nguyễn Tất Thành",
//             type: true,
//             isBoth: false,
//             firstNumber: 401,
//             lastNumber: 999,
//             route: "O2",
//         },
//         {
//             streetName: "Trần Cao Vân (276-340)",
//             type: true,
//             isBoth: false,
//             firstNumber: 276,
//             lastNumber: 340,
//             route: "O2",
//         },
//         {
//             streetName: "Tôn Thất Đạm",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O2",
//         },
//     ],
//     O4: [
//         {
//             streetName: "Thái Thị Bôi",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Hà Xuân 1",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Hà Xuân 2",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Lê Quang Sung",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Lê Thị Xuyến",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Ngô Gia Khảm",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Xuân Hòa 1",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O4",
//         },
//         {
//             streetName: "Hà Huy Tập (70-122)",
//             type: true,
//             isBoth: false,
//             firstNumber: 70,
//             lastNumber: 122,
//             route: "O4",
//         },
//         {
//             streetName: "Hà Huy Tập (57-113)",
//             type: true,
//             isBoth: false,
//             firstNumber: 57,
//             lastNumber: 113,
//             route: "O4",
//         },
//     ],
//     O5: [
//         {
//             streetName: "Võ Văn Tần",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O5",
//         },
//         {
//             streetName: "Lê Độ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O5",
//         },
//         {
//             streetName: "Trần Cao Vân (91-207)",
//             type: true,
//             isBoth: false,
//             firstNumber: 91,
//             lastNumber: 207,
//             route: "O5",
//         },
//         {
//             streetName: "Trần Cao Vân (200-274)",
//             type: true,
//             isBoth: false,
//             firstNumber: 200,
//             lastNumber: 274,
//             route: "O5",
//         },
//         {
//             streetName: "Thuận An 1-6",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O5",
//         },
//     ],
//     O6: [
//         {
//             streetName: "Điện Biên Phủ (0-218)",
//             type: true,
//             isBoth: false,
//             firstNumber: 0,
//             lastNumber: 218,
//             route: "O6",
//         },
//         {
//             streetName: "Điện Biên Phủ (1-325)",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 325,
//             route: "O6",
//         },
//         {
//             streetName: "Bế Văn Đàn",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O6",
//         },
//         {
//             streetName: "Lê Duy Đình",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O6",
//         },
//     ],
//     O7: [
//         {
//             streetName: "Hà Huy Tập (115-Hết)",
//             type: true,
//             isBoth: false,
//             firstNumber: 115,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Hà Huy Tập (124-Hết)",
//             type: true,
//             isBoth: false,
//             firstNumber: 124,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Nguyễn Hồng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Nguyễn Biểu",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Nguyễn Nghiêm",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Thân Nhân Trung",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Đoàn Nhữ Hài",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Huỳnh Ngọc Huệ (Chẵn)",
//             type: true,
//             isBoth: false,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//         {
//             streetName: "Hà Huy Tập (1-55)",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 55,
//             route: "O7",
//         },
//         {
//             streetName: "Hà Huy Tập (2-68)",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 68,
//             route: "O7",
//         },
//         {
//             streetName: "Mai xuân thưởng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O7",
//         },
//     ],
//     O8: [
//         {
//             streetName: "Nguyễn Đức Trung",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Xuân Hoà 2",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Nguyễn Tất Thành (1263-1449)",
//             type: true,
//             isBoth: false,
//             firstNumber: 1263,
//             lastNumber: 1449,
//             route: "O8",
//         },
//         {
//             streetName: "Nguyễn Cao",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Thanh Huy 1 2 3",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Yên Khê 2",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Nguyễn Huy Lượng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Đặng Đình Vân",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Kỳ Đồng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Hà Đông 1,2,3",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Đặng Đình Vân",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Bàu Làng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//         {
//             streetName: "Nguyễn Văn Huề",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O8",
//         },
//     ],
//     O10: [
//         {
//             streetName: "Điện biên phủ (220-760)",
//             type: true,
//             isBoth: false,
//             firstNumber: 220,
//             lastNumber: 760,
//             route: "O10",
//         },
//         {
//             streetName: "Điện biên phủ (327-727)",
//             type: true,
//             isBoth: false,
//             firstNumber: 327,
//             lastNumber: 727,
//             route: "O10",
//         },
//         {
//             streetName: "Bàu Trảng 1-7",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O10",
//         },
//         {
//             streetName: "Mẹ Nhu",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O10",
//         },
//     ],
//     O11: [
//         {
//             streetName: "Điện biên phủ(130-354)",
//             type: true,
//             isBoth: false,
//             firstNumber: 130,
//             lastNumber: 354,
//             route: "O10",
//         },
//         {
//             streetName: "Điện biên phủ(327-433)",
//             type: true,
//             isBoth: false,
//             firstNumber: 327,
//             lastNumber: 433,
//             route: "O10",
//         },
//         {
//             streetName: "Mai xuân thưởng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O10",
//         },
//         {
//             streetName: "Bế Văn Đàn (185-Hết)",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O10",
//         },
//         {
//             streetName: "Hà Huy Tập (1-23)",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 23,
//             route: "O10",
//         },
//         {
//             streetName: "Hà Huy Tập (2-40)",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 40,
//             route: "O10",
//         },
//     ],
//     O12: [
//         {
//             streetName: "Trần Cao Vân (657-Hết)",
//             type: true,
//             isBoth: false,
//             firstNumber: 657,
//             lastNumber: 10000,
//             route: "O12",
//         },
//         {
//             streetName: "Trần Cao Vân (732-Hết)",
//             type: true,
//             isBoth: false,
//             firstNumber: 732,
//             lastNumber: 10000,
//             route: "O12",
//         },
//         {
//             streetName: "Hà Khê (K2 > 100)",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 100,
//             route: "O12",
//         },
//         {
//             streetName: "Nguyễn Tất Thành (999-1261)",
//             type: true,
//             isBoth: false,
//             firstNumber: 999,
//             lastNumber: 1261,
//             route: "O12",
//         },
//         {
//             streetName: "Thanh Tân",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O12",
//         },
//         {
//             streetName: "Mẹ Hiền",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O12",
//         },
//         {
//             streetName: "Trần Thanh Trung",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O12",
//         },
//         {
//             streetName: "Nguyễn Văn Phương",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O12",
//         },
//     ],
//     O14: [
//         {
//             streetName: "Lê Duẩn (185-319)",
//             type: true,
//             isBoth: false,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O14",
//         },
//         {
//             streetName: "Lê Duẩn (188-318)",
//             type: true,
//             isBoth: false,
//             firstNumber: 188,
//             lastNumber: 318,
//             route: "O14",
//         },
//         {
//             streetName: "Hùng Vương(257-341)",
//             type: true,
//             isBoth: false,
//             firstNumber: 257,
//             lastNumber: 341,
//             route: "O14",
//         },
//         {
//             streetName: "Hùng Vương(292-438)",
//             type: true,
//             isBoth: false,
//             firstNumber: 292,
//             lastNumber: 438,
//             route: "O14",
//         },
//         {
//             streetName: "Ông Ích Khiêm (424-458)",
//             type: true,
//             isBoth: false,
//             firstNumber: 424,
//             lastNumber: 458,
//             route: "O14",
//         },
//         {
//             streetName: "Hải Phòng (175-281)",
//             type: true,
//             isBoth: false,
//             firstNumber: 175,
//             lastNumber: 281,
//             route: "O14",
//         },
//     ],
//     O15: [
//         {
//             streetName: "Hải Phòng (166-322)",
//             type: true,
//             isBoth: false,
//             firstNumber: 166,
//             lastNumber: 322,
//             route: "O15",
//         },
//         {
//             streetName: "Lý Thái Tổ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O15",
//         },
//         {
//             streetName: "Hoàng Hoa Thám",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O15",
//         },
//     ],
//     O16: [
//         {
//             streetName: "Đào Duy Từ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O16",
//         },
//         {
//             streetName: "Lê Ngô Cát",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O16",
//         },
//         {
//             streetName: "Ông Ích Khiêm (152-422)",
//             type: true,
//             isBoth: false,
//             firstNumber: 152,
//             lastNumber: 422,
//             route: "O16",
//         },
//         {
//             streetName: "Trần Cao Vân (1-89)",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 89,
//             route: "O16",
//         },
//         {
//             streetName: "Trần Cao Vân (2-198)",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 198,
//             route: "O16",
//         },
//     ],
//         {
//             streetName: "Vĩnh Trung plaza (255-257 Hùng Vương )",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O18",
//         },
//         {
//             streetName: "Lê Duẩn (320-478)",
//             type: true,
//             isBoth: false,
//             firstNumber: 320,
//             lastNumber: 478,
//             route: "O18",
//         },
//         {
//             streetName: "Lê Duẩn (321-461)",
//             type: true,
//             isBoth: false,
//             firstNumber: 321,
//             lastNumber: 461,
//             route: "O18",
//         },
//         {
//             streetName: "Hải Phòng (283-461)",
//             type: true,
//             isBoth: false,
//             firstNumber: 283,
//             lastNumber: 461,
//             route: "O18",
//         },
//         {
//             streetName: "Phần Lăng 1-19",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Thúc Tề",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Đinh Núp",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Trần Can",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Nguyễn Công Hãng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Huỳnh Ngọc Huệ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "Lý Triện",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O20",
//         },
//         {
//             streetName: "1 - 89 Cù Chính Lan",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 189,
//             route: "O21",
//         },
//         {
//             streetName: "2 - 180 Cù Chính Lan",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 180,
//             route: "O21",
//         },
//         {
//             streetName: "An Xuân 1",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//         {
//             streetName: "An Xuân 2",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//         {
//             streetName: "Trần Xuân Lê",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//         {
//             streetName: "Hồ Tương",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//         {
//             streetName: "Nguyễn Đăng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//         {
//             streetName: "Nguyễn Đình Tựu (từ 180 trở lên)",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O21",
//         },
//     O22: [
//         {
//             streetName: "91-165 Cù Chính Lan",
//             type: true,
//             isBoth: false,
//             firstNumber: 91,
//             lastNumber: 165,
//             route: "O22",
//         },
//         {
//             streetName: "182-282 Cù Chính Lan",
//             type: true,
//             isBoth: false,
//             firstNumber: 182,
//             lastNumber: 282,
//             route: "O22",
//         },
//         {
//             streetName: "Phạm Nhữ Tăng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O22",
//         },
//         {
//             streetName: "Nguyễn Phước Thái",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O22",
//         },
//         {
//             streetName: "1-221 Trường Chinh",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 221,
//             route: "O23",
//         },
//         {
//             streetName: "1 - 323 Nguyễn Phước Nguyên",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 323,
//             route: "O23",
//         },
//         {
//             streetName: "2 - 330 Nguyễn Phước Nguyên",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 330,
//             route: "O23",
//         },
//         {
//             streetName: "Nguyễn Giản Thanh",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O23",
//         },
//         {
//             streetName: "Cần Giuộc",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O23",
//         },
//         {
//             streetName: "Nguyễn Khang",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O23",
//         },
//         {
//             streetName: "Nguyễn Đình Tựu (2-180)",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O23",
//         },
//         {
//             streetName: "223-311 Trường Chinh",
//             type: true,
//             isBoth: false,
//             firstNumber: 223,
//             lastNumber: 311,
//             route: "O24",
//         },
//         {
//             streetName: "Đinh Thị Vân",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//         {
//             streetName: "Đặng Phúc Thông",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//         {
//             streetName: "325-799 Nguyễn Phước Nguyên",
//             type: true,
//             isBoth: false,
//             firstNumber: 325,
//             lastNumber: 799,
//             route: "O24",
//         },
//         {
//             streetName: "332-700 Nguyễn Phước Nguyên",
//             type: true,
//             isBoth: false,
//             firstNumber: 332,
//             lastNumber: 700,
//             route: "O24",
//         },
//         {
//             streetName: "Đông Lợi 1",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//         {
//             streetName: "Đông Lợi 2",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//         {
//             streetName: "Đông Lợi 3",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//         {
//             streetName: "Đông Lợi 4",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O24",
//         },
//     ],
//     O25: [
//         {
//             streetName: "313-553 Trường Chinh",
//             type: true,
//             isBoth: false,
//             firstNumber: 313,
//             lastNumber: 553,
//             route: "O25",
//         },
//         {
//             streetName: "Trần Thái Tông",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "Đỗ Đức Dục",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "1-17 Lê Trọng Tấn",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 17,
//             route: "O25",
//         },
//         {
//             streetName: "2-20 Lê Trọng Tấn",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 20,
//             route: "O25",
//         },
//         {
//             streetName: "Nguyễn Thành Năm",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "Nguyễn Hữu Thuận",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "Phạm Ngọc Mậu",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "Phan Xích Long",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O25",
//         },
//         {
//             streetName: "Tân Hòa 1-10",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 10,
//             route: "O25",
//         },
//         {
//             streetName: "74-182 Bạch Đằng",
//             type: true,
//             isBoth: false,
//             firstNumber: 74,
//             lastNumber: 182,
//             route: "O26",
//         },
//         {
//             streetName: "40-168 Trần Phú",
//             type: true,
//             isBoth: false,
//             firstNumber: 40,
//             lastNumber: 168,
//             route: "O26",
//         },
//         {
//             streetName: "53-185 Trần Phú",
//             type: true,
//             isBoth: false,
//             firstNumber: 53,
//             lastNumber: 185,
//             route: "O26",
//         },
//         {
//             streetName: "Phạm Phú Thứ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O26",
//         },
//         {
//             streetName: "Chợ Hàn",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O26",
//         },
//         {
//             streetName: "Toà nhà Indochina",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O26",
//         },
//         {
//             streetName: "2-36 Hùng Vương",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 36,
//             route: "O26",
//         },
//         {
//             streetName: "1-9 Hùng Vương",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 9,
//             route: "O26",
//         },
//         {
//             streetName: "Cô Giang",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O26",
//         },
//         {
//             streetName: "2-186 Lê Duẩn",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 186,
//             route: "O27",
//         },
//         {
//             streetName: "3-183 Lê Duẩn",
//             type: true,
//             isBoth: false,
//             firstNumber: 3,
//             lastNumber: 183,
//             route: "O27",
//         },
//         {
//             streetName: "188-290 Hùng Vương",
//             type: true,
//             isBoth: false,
//             firstNumber: 188,
//             lastNumber: 290,
//             route: "O27",
//         },
//         {
//             streetName: "115-251 Hùng Vương",
//             type: true,
//             isBoth: false,
//             firstNumber: 115,
//             lastNumber: 251,
//             route: "O27",
//         },
//         {
//             streetName: "2-32 Ngô Gia Tự",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 32,
//             route: "O27",
//         },
//         {
//             streetName: "1-11 Ngô Gia Tự",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 11,
//             route: "O27",
//         },
//         {
//             streetName: "118-210 Nguyễn Chí Thanh",
//             type: true,
//             isBoth: false,
//             firstNumber: 118,
//             lastNumber: 210,
//             route: "O27",
//         },
//         {
//             streetName: "199-301 Nguyễn Chí Thanh",
//             type: true,
//             isBoth: false,
//             firstNumber: 199,
//             lastNumber: 301,
//             route: "O27",
//         },
//         {
//             streetName: "2-142 Yên Bái",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 142,
//             route: "O27",
//         },
//         {
//             streetName: "1-101 Yên Bái",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 101,
//             route: "O27",
//         },
//     ],
//     O28: [
//         {
//             streetName: "2-158 Phan Châu Trinh",
//             type: true,
//             isBoth: false,
//             firstNumber: 2,
//             lastNumber: 158,
//             route: "O28",
//         },
//         {
//             streetName: "1-185 Phan Châu Trinh",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 185,
//             route: "O28",
//         },
//         {
//             streetName: "Phan Đình Phùng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O28",
//         },
//         {
//             streetName: "Phạm Hồng Thái",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O28",
//         },
//         {
//             streetName: "Nguyễn Thái Học",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O28",
//         },
//         {
//             streetName: "Trần Quốc Toản",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O28",
//         },
//         {
//             streetName: "464-528 Ông Ích Khiêm",
//             type: true,
//             isBoth: false,
//             firstNumber: 464,
//             lastNumber: 528,
//             route: "O29",
//         },
//         {
//             streetName: "153-385 Ông Ích Khiêm",
//             type: true,
//             isBoth: false,
//             firstNumber: 153,
//             lastNumber: 385,
//             route: "O29",
//         },
//         {
//             streetName: "Chợ Cồn",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O29",
//         },
//         {
//             streetName: "34-110 Ngô Gia Tự",
//             type: true,
//             isBoth: false,
//             firstNumber: 34,
//             lastNumber: 110,
//             route: "O29",
//         },
//         {
//             streetName: "13-151 Ngô Gia Tự",
//             type: true,
//             isBoth: false,
//             firstNumber: 13,
//             lastNumber: 151,
//             route: "O29",
//         },
//         {
//             streetName: "Chi Lăng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O29",
//         },
//         {
//             streetName: "Trần Bình Trọng",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O29",
//         },
//         {
//             streetName: "1-163 Nguyễn Hoàng",
//             type: true,
//             isBoth: false,
//             firstNumber: 1,
//             lastNumber: 163,
//             route: "O29",
//         },
//         {
//             streetName: "187-258 Bạch Đằng",
//             type: true,
//             isBoth: false,
//             firstNumber: 187,
//             lastNumber: 258,
//             route: "O30",
//         },
//         {
//             streetName: "170-270 Trần Phú",
//             type: true,
//             isBoth: false,
//             firstNumber: 170,
//             lastNumber: 270,
//             route: "O30",
//         },
//         {
//             streetName: "187-265 Trần Phú",
//             type: true,
//             isBoth: false,
//             firstNumber: 187,
//             lastNumber: 265,
//             route: "O30",
//         },
//         {
//             streetName: "Thái Phiên",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O30",
//         },
//         {
//             streetName: "Hoàng Văn Thụ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O30",
//         },
//         {
//             streetName: "Lê Đình Dương",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O30",
//         },
//     ],
//     O31: [
//         {
//             streetName: "530-626 Ông Ích Khiêm",
//             type: true,
//             isBoth: false,
//             firstNumber: 530,
//             lastNumber: 626,
//             route: "O31",
//         },
//         {
//             streetName: "387-465 Ông Ích Khiêm",
//             type: true,
//             isBoth: false,
//             firstNumber: 387,
//             lastNumber: 465,
//             route: "O31",
//         },
//         {
//             streetName: "Triệu Nữ Vương",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Trần Kế Xương",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Mạc Đỉnh Chi",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Đoàn Thị Điểm",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Tăng Bạt Hổ",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Cô Bắc",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Phạm Ngũ Lão",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//         {
//             streetName: "Nguyễn Trãi",
//             type: true,
//             isBoth: true,
//             firstNumber: 0,
//             lastNumber: 10000,
//             route: "O31",
//         },
//     ],
// };

const CODS = {
    O2: { name: "Nguyễn Hồng Sơn", phone: "0934000990", route: "O2" },
    O4: { name: "Phan Hùng Khánh", phone: "0935092313", route: "O4" },
    O5: { name: "Trần Triệu Long", phone: "0796021773", route: "O5" },
    O6: { name: "Trương Thạnh", phone: "0776155351", route: "O6" },
    O7: { name: "Huỳnh Châu Anh Đức", phone: "0934844188", route: "O7" },
    O8: { name: "Lê Anh Tuấn", phone: "0936284142", route: "O8" },
    O10: { name: "Phạm Văn Bình", phone: "0777529193", route: "O10" },
    O12: { name: "Huỳnh Ngọc Chiến", phone: "0905557464", route: "O12" },
    O14: { name: "Đỗ Vũ Quốc Thịnh", phone: "0766663739", route: "O14" },
    O15: { name: "Nguyễn Văn Đức", phone: "0935600326", route: "O15" },
    O16: { name: "Hồ Thiện Thành", phone: "0932552600", route: "O16" },
    O18: { name: "Dương Minh Triều", phone: "0772496989", route: "O18" },
    O20: { name: "Võ Thành Phước", phone: "0935190822", route: "O20" },
    O21: { name: "Lê Tấn Huỳnh Lynh", phone: "0905212957", route: "O21" },
    O22: { name: "Phan Hòa", phone: "0772444406", route: "O22" },
    O23: { name: "Đào Ngọc Thời", phone: "0905788184", route: "O23" },
    O24: { name: "Nguyễn Viết Triều", phone: "0905783799", route: "O24" },
    O25: { name: "Nguyễn Duy Thành", phone: "0971997249", route: "O25" },
    O26: { name: "Phan Huỳnh Đạo", phone: "0932522556", route: "O26" },
    O27: { name: "Lê Phú Tuấn", phone: "0905808941", route: "O27" },
    O28: { name: "Huỳnh Ngọc Nghĩa", phone: "0905506594", route: "O28" },
    O29: { name: "Ngô Đặng Thị Minh Ngọc", phone: "0905042047", route: "O29" },
    O30: { name: "Phạm Văn Thanh", phone: "0936008505", route: "O30" },
    O31: { name: "Dương Hiển Sáng", phone: "0793590393", route: "O31" },
    O32: { name: "Nguyễn Quang Hưng", phone: "0901912932", route: "O32" },
};
