const MAIN_ROUTES = {
    // O1: [
    //     {
    //         streetName: "Trần Cao Vân",
    //         type: "Odd",
    //         firstNumber: 1,
    //         lastNumber: 89,
    //         route: "O1",
    //     },
    //     {
    //         streetName: "Trần Cao Vân (2-274)",
    //         type: "Even",
    //         firstNumber: 2,
    //         lastNumber: 274,
    //         route: "O1",
    //     },
    // ],
    O2: [
        {
            streetName: "Trần Cao Vân (209-337)",
            type: "Odd",
            firstNumber: 209,
            lastNumber: 337,
            route: "O2",
        },
        {
            streetName: "Trần Cao Vân (342-624)",
            type: "Even",
            firstNumber: 342,
            lastNumber: 426,
            route: "O2",
        },
        {
            streetName: "Nguyễn Tất Thành",
            type: "Odd",
            firstNumber: 401,
            lastNumber: 999,
            route: "O2",
        },
        {
            streetName: "Trần Cao Vân (276-340)",
            type: "Even",
            firstNumber: 276,
            lastNumber: 340,
            route: "O2",
        },
        {
            streetName: "Tôn Thất Đạm",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O2",
        },
    ],
    O4: [
        {
            streetName: "Thái Thị Bôi",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Hà Xuân 1",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Hà Xuân 2",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Lê Quang Sung",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Lê Thị Xuyến",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Ngô Gia Khảm",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Xuân Hòa 1",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O4",
        },
        {
            streetName: "Hà Huy Tập",
            type: "Even",
            firstNumber: 70,
            lastNumber: 122,
            route: "O4",
        },
        {
            streetName: "Hà Huy Tập",
            type: "Even",
            firstNumber: 57,
            lastNumber: 113,
            route: "O4",
        },
    ],
    O5: [
        {
            streetName: "Võ Văn Tần",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O5",
        },
        {
            streetName: "Lê Độ",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O5",
        },
        {
            streetName: "Trần Cao Vân (91-207)",
            type: "Odd",
            firstNumber: 91,
            lastNumber: 207,
            route: "O5",
        },
        {
            streetName: "Trần Cao Vân (200-274)",
            type: "Even",
            firstNumber: 200,
            lastNumber: 274,
            route: "O5",
        },
        {
            streetName: "Thuận An 1-6",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O5",
        },
    ],
    O6: [
        {
            streetName: "Điện Biên Phủ (0-218)",
            type: "Even",
            firstNumber: 0,
            lastNumber: 218,
            route: "O6",
        },
        {
            streetName: "Điện Biên Phủ (1-325)",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 325,
            route: "O6",
        },
        {
            streetName: "Bế Văn Đàn",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O6",
        },
        {
            streetName: "Lê Duy Đình",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O6",
        },
    ],
    O7: [
        {
            streetName: "Hà Huy Tập (115-Hết)",
            type: "Odd",
            firstNumber: 115,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Hà Huy Tập (124-Hết)",
            type: "Even",
            firstNumber: 124,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Nguyễn Hồng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Nguyễn Biểu",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Nguyễn Nghiêm",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Thân Nhân Trung",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Đoàn Nhữ Hài",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Huỳnh Ngọc Huệ (Chẵn)",
            type: "Even",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
        {
            streetName: "Hà Huy Tập (1-55)",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 55,
            route: "O7",
        },
        {
            streetName: "Hà Huy Tập (2-68)",
            type: "Even",
            firstNumber: 2,
            lastNumber: 68,
            route: "O7",
        },
        {
            streetName: "Mai xuân thưởng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O7",
        },
    ],
    O8: [
        {
            streetName: "Nguyễn Đức Trung",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Xuân Hoà 2",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Nguyễn Tất Thành (1263-1449)",
            type: "Odd",
            firstNumber: 1263,
            lastNumber: 1449,
            route: "O8",
        },
        {
            streetName: "Nguyễn Cao",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Thanh Huy 1 2 3",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Yên Khê 2",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Nguyễn Huy Lượng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Đặng Đình Vân",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Kỳ Đồng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Hà Đông 1,2,3",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Đặng Đình Vân",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Bàu Làng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
        {
            streetName: "Nguyễn Văn Huề",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O8",
        },
    ],
    O10: [
        {
            streetName: "Điện biên phủ (220-760)",
            type: "Even",
            firstNumber: 220,
            lastNumber: 760,
            route: "O10",
        },
        {
            streetName: "Điện biên phủ (327-727)",
            type: "Even",
            firstNumber: 327,
            lastNumber: 727,
            route: "O10",
        },
        {
            streetName: "Bàu Trảng 1-7",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O10",
        },
        {
            streetName: "Mẹ Nhu",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O10",
        },
    ],
    O11: [
        {
            streetName: "Điện biên phủ(130-354)",
            type: "Even",
            firstNumber: 130,
            lastNumber: 354,
            route: "O10",
        },
        {
            streetName: "Điện biên phủ(327-433)",
            type: "Odd",
            firstNumber: 327,
            lastNumber: 433,
            route: "O10",
        },
        {
            streetName: "Mai xuân thưởng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O10",
        },
        {
            streetName: "Bế Văn Đàn (185-Hết)",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O10",
        },
        {
            streetName: "Hà Huy Tập (1-23)",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 23,
            route: "O10",
        },
        {
            streetName: "Hà Huy Tập (2-40)",
            type: "Even",
            firstNumber: 2,
            lastNumber: 40,
            route: "O10",
        },
    ],
    O12: [
        {
            streetName: "Trần Cao Vân (657-Hết)",
            type: "Odd",
            firstNumber: 657,
            lastNumber: Infinity,
            route: "O12",
        },
        {
            streetName: "Trần Cao Vân (732-Hết)",
            type: "Even",
            firstNumber: 732,
            lastNumber: Infinity,
            route: "O12",
        },
        {
            streetName: "Hà Khê (K2 > 100)",
            type: "Both",
            firstNumber: 0,
            lastNumber: 100,
            route: "O12",
        },
        {
            streetName: "Nguyễn Tất Thành (999-1261)",
            type: "Odd",
            firstNumber: 999,
            lastNumber: 1261,
            route: "O12",
        },
        {
            streetName: "Thanh Tân",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O12",
        },
        {
            streetName: "Mẹ Hiền",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O12",
        },
        {
            streetName: "Trần Thanh Trung",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O12",
        },
        {
            streetName: "Nguyễn Văn Phương",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O12",
        },
    ],
    O14: [
        {
            streetName: "Lê Duẩn (185-319)",
            type: "Odd",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O14",
        },
        {
            streetName: "Lê Duẩn (188-318)",
            type: "Even",
            firstNumber: 188,
            lastNumber: 318,
            route: "O14",
        },
        {
            streetName: "Hùng Vương(257-341)",
            type: "Odd",
            firstNumber: 257,
            lastNumber: 341,
            route: "O14",
        },
        {
            streetName: "Hùng Vương(292-438)",
            type: "Even",
            firstNumber: 292,
            lastNumber: 438,
            route: "O14",
        },
        {
            streetName: "Ông Ích Khiêm (424-458)",
            type: "Even",
            firstNumber: 424,
            lastNumber: 458,
            route: "O14",
        },
        {
            streetName: "Hải Phòng (175-281)",
            type: "Odd",
            firstNumber: 175,
            lastNumber: 281,
            route: "O14",
        },
    ],
    O15: [
        {
            streetName: "Hải Phòng (166-322)",
            type: "Even",
            firstNumber: 166,
            lastNumber: 322,
            route: "O15",
        },
        {
            streetName: "Lý Thái Tổ",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O15",
        },
        {
            streetName: "Hoàng Hoa Thám",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O15",
        },
    ],
    O16: [
        {
            streetName: "Đào Duy Từ",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O16",
        },
        {
            streetName: "Lê Ngô Cát",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O16",
        },
        {
            streetName: "Ông Ích Khiêm (152-422)",
            type: "Even",
            firstNumber: 152,
            lastNumber: 422,
            route: "O16",
        },
        {
            streetName: "Trần Cao Vân (1-89)",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 89,
            route: "O16",
        },
        {
            streetName: "Trần Cao Vân (2-198)",
            type: "Even",
            firstNumber: 2,
            lastNumber: 198,
            route: "O16",
        },
    ],
    O18: [
        {
            streetName: "Vĩnh Trung plaza (255-257 Hùng Vương )",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O18",
        },
        {
            streetName: "Lê Duẩn (320-478)",
            type: "Even",
            firstNumber: 320,
            lastNumber: 478,
            route: "O18",
        },
        {
            streetName: "Lê Duẩn (321-461)",
            type: "Odd",
            firstNumber: 321,
            lastNumber: 461,
            route: "O18",
        },
        {
            streetName: "Hải Phòng (283-461)",
            type: "Odd",
            firstNumber: 283,
            lastNumber: 461,
            route: "O18",
        },
    ],
    O20: [
        {
            streetName: "Phần Lăng 1-19",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Thúc Tề",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Đinh Núp",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Trần Can",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Nguyễn Công Hãng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Huỳnh Ngọc Huệ",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
        {
            streetName: "Lý Triện",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O20",
        },
    ],
    O21: [
        {
            streetName: "1 - 89 Cù Chính Lan",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 189,
            route: "O21",
        },
        {
            streetName: "2 - 180 Cù Chính Lan",
            type: "Even",
            firstNumber: 2,
            lastNumber: 180,
            route: "O21",
        },
        {
            streetName: "An Xuân 1",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
        {
            streetName: "An Xuân 2",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
        {
            streetName: "Trần Xuân Lê",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
        {
            streetName: "Hồ Tương",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
        {
            streetName: "Nguyễn Đăng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
        {
            streetName: "Nguyễn Đình Tựu (từ 180 trở lên)",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O21",
        },
    ],
    O22: [
        {
            streetName: "91-165 Cù Chính Lan",
            type: "Odd",
            firstNumber: 91,
            lastNumber: 165,
            route: "O22",
        },
        {
            streetName: "182-282 Cù Chính Lan",
            type: "Even",
            firstNumber: 182,
            lastNumber: 282,
            route: "O22",
        },
        {
            streetName: "Phạm Nhữ Tăng",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O22",
        },
        {
            streetName: "Nguyễn Phước Thái",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O22",
        },
    ],
    O23: [
        {
            streetName: "1-221 Trường Chinh",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 221,
            route: "O23",
        },
        {
            streetName: "1 - 323 Nguyễn Phước Nguyên",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 323,
            route: "O23",
        },
        {
            streetName: "2 - 330 Nguyễn Phước Nguyên",
            type: "Even",
            firstNumber: 2,
            lastNumber: 330,
            route: "O23",
        },
        {
            streetName: "Nguyễn Giản Thanh",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O23",
        },
        {
            streetName: "Cần Giuộc",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O23",
        },
        {
            streetName: "Nguyễn Khang",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O23",
        },
        {
            streetName: "Nguyễn Đình Tựu (2-180)",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O23",
        },
    ],
    O24: [
        {
            streetName: "223-311 Trường Chinh",
            type: "Odd",
            firstNumber: 223,
            lastNumber: 311,
            route: "O24",
        },
        {
            streetName: "Đinh Thị Vân",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
        {
            streetName: "Đặng Phúc Thông",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
        {
            streetName: "325-799 Nguyễn Phước Nguyên",
            type: "Odd",
            firstNumber: 325,
            lastNumber: 799,
            route: "O24",
        },
        {
            streetName: "332-700 Nguyễn Phước Nguyên",
            type: "Even",
            firstNumber: 332,
            lastNumber: 700,
            route: "O24",
        },
        {
            streetName: "Đông Lợi 1",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
        {
            streetName: "Đông Lợi 2",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
        {
            streetName: "Đông Lợi 3",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
        {
            streetName: "Đông Lợi 4",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O24",
        },
    ],
    O25: [
        {
            streetName: "313-553 Trường Chinh",
            type: "Odd",
            firstNumber: 313,
            lastNumber: 553,
            route: "O25",
        },
        {
            streetName: "Trần Thái Tông",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "Đỗ Đức Dục",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "1-17 Lê Trọng Tấn",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 17,
            route: "O25",
        },
        {
            streetName: "2-20 Lê Trọng Tấn",
            type: "Even",
            firstNumber: 2,
            lastNumber: 20,
            route: "O25",
        },
        {
            streetName: "Nguyễn Thành Năm",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "Nguyễn Hữu Thuận",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "Phạm Ngọc Mậu",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "Phan Xích Long",
            type: "Both",
            firstNumber: 0,
            lastNumber: Infinity,
            route: "O25",
        },
        {
            streetName: "Tân Hòa 1-10",
            type: "Odd",
            firstNumber: 1,
            lastNumber: 10,
            route: "O25",
        },
    ],
};

const CODS = {
    O2: { name: "Nguyễn Hồng Sơn", phone: "0990" },
    O4: { name: "Phan Hùng Khánh", phone: "2313" },
    O5: { name: "Trần Triệu Long", phone: "1773" },
    O6: { name: "Trương Thạnh", phone: "5351" },
    O7: { name: "Huỳnh Châu Anh Đức", phone: "4188" },
    O8: { name: "Dương Đông Hưng", phone: "9975" },
    O10: { name: "Phạm Văn Bình", phone: "9193" },
    O12: { name: "Huỳnh Ngọc Chiến", phone: "7464" },
    O14: { name: "Đỗ Vũ Quốc Thịnh", phone: "3739" },
    O15: { name: "Nguyễn Văn Đức", phone: "0326" },
    O16: { name: "Nguyễn Hùng Trung", phone: "4552" },
    O18: { name: "Dương Minh Triều", phone: "6989" },
    O20: { name: "Võ Thành Phước", phone: "0822" },
    O21: { name: "Lê Tấn Huỳnh Lynh", phone: "2957" },
    O22: { name: "Phan Hòa", phone: "4406" },
    O23: { name: "Đào Ngọc Thời", phone: "8184" },
    O24: { name: "Nguyễn Viết Triều", phone: "3799" },
    O25: { name: "Nguyễn Duy Thành", phone: "7249" },
    O26: { name: "Phan Huỳnh Đạo", phone: "2556" },
    O27: { name: "Lê Phú Tuấn", phone: "8941" },
    O28: { name: "Huỳnh Ngọc Nghĩa", phone: "6594" },
    O29: { name: "Ngô Đặng Thị Minh Ngọc", phone: "2047" },
    O30: { name: "Phạm Văn Thanh", phone: "8505" },
    O31: { name: "Dương Hiển Sáng", phone: "0393" },
    O32: { name: "Nguyễn Quang Hưng", phone: "2932" },
    _: { name: "Lê Anh Tuấn", phone: "4142" },
};
